kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  template:
    spec:
      containers:
      - name: nginx-replace
        image: nginx-2.0
      - $patch: replace  # recursive and applies to all fields of the map it's in