apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
spec:
  rules:
  - host: host1.example.com
    http:
      paths:
      - backend:
          service:
            name: server
            port:
              number: 80